[package]
name = "bevy_input_prompts"
version = "0.1.0"
edition = "2024"
include = ["src/**/*", "assets/bevy_input_prompts/**/*", "Cargo.toml"]

[dependencies]
bevy_asset = "0.15"
bevy_input = "0.15"
fs_extra = "1.3.0"

[dev-dependencies]
bevy = "0.15"

[workspace]
members = ["asset_gen", "coverage"]
