[package]
name = "bevy_input_prompts"
version = "0.1.0"
edition = "2024"
include = ["src/**/*", "assets/bevy_input_prompts/**/*", "Cargo.toml"]
license = "MIT"
description = "Mappings from bevy input types to popular input prompt asset paths"
homepage = "https://github.com/jonathandw743/bevy_input_prompts"
repository = "https://github.com/jonathandw743/bevy_input_prompts"

[dependencies]
bevy_asset = "0.15"
bevy_input = "0.15"
fs_extra = "1.3.0"
bevy_input_prompts_macros = { path = "macros" }
walkdir = "2.5.0"
petgraph = "0.8.1"
itertools = "0.14.0"
bimap = "0.6.3"
fixedbitset = "0.5.7"

[dev-dependencies]
bevy = "0.15"

[workspace]
members = ["asset_gen", "coverage", "macros"]

[build-dependencies]
proc-macro2 = "1.0.94"
quote = "1.0.40"
syn = "2.0.100"
