[package]
name = "bevy_input_prompts_macros"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
bit-set = "0.8.0"
hashbrown = "0.15.2"
petgraph = "0.8.1"
proc-macro2 = "1.0.94"
quote = "1.0.40"
syn = "2.0.100"

[lib]
proc-macro = true
