use bevy_input::gamepad::GamepadButton::{self, *};

use crate::{
    Pack, FileIndices,
    gamepad_brand::GamepadBrand::{self, *},
};

impl FileIndices for (GamepadBrand, GamepadButton) {
    fn file_indices<'a, 'b>(&self, pack: Pack) -> Option<&'a [&'b [usize]]> {
        match pack {
            #[cfg(feature = "use_kenney_input_prompts")]
            Pack::Kenney => {
                use kenney_input_prompts::tokenize_dir::_kenney_input_prompts_1_4::{
                    _Generic::stem_words as generic, _Nintendo_Gamecube::stem_words as gamecube,
                    _Nintendo_Switch::stem_words as switch,
                    _Nintendo_Switch_2::stem_words as switch2, _Nintendo_Wii::stem_words as wii,
                    _Nintendo_WiiU::stem_words as wiiu, _PlayStation_Series::stem_words as ps,
                    _Playdate::stem_words as playdate, _Steam_Controller::stem_words as steam,
                    _Steam_Deck::stem_words as steamdeck, _Xbox_Series::stem_words as xbox,
                };
                match self {
                    (Generic, South | East | North | West) => {
                        Some(&[generic::_button, generic::_circle])
                    }
                    (Generic, C) => None,
                    (Generic, Z) => None,
                    (Generic, LeftTrigger | LeftTrigger2 | RightTrigger | RightTrigger2) => {
                        Some(&[generic::_trigger])
                    }
                    (Generic, Select) => None,
                    (Generic, Start) => None,
                    (Generic, Mode) => None,
                    (Generic, LeftThumb | RightThumb) => Some(&[generic::_press, generic::_stick]),
                    (Generic, DPadUp) => None,
                    (Generic, DPadDown) => None,
                    (Generic, DPadLeft) => None,
                    (Generic, DPadRight) => None,
                    (Generic, Other(_)) => None,

                    (Gamecube, South) => Some(&[gamecube::_a]),
                    (Gamecube, East) => Some(&[gamecube::_b]),
                    (Gamecube, North) => Some(&[gamecube::_y]),
                    (Gamecube, West) => Some(&[gamecube::_x]),
                    (Gamecube, C) => None,
                    (Gamecube, Z) => None,
                    (Gamecube, LeftTrigger) => None,
                    (Gamecube, LeftTrigger2) => None,
                    (Gamecube, RightTrigger) => None,
                    (Gamecube, RightTrigger2) => None,
                    (Gamecube, Select) => None,
                    (Gamecube, Start) => Some(&[gamecube::_start]),
                    (Gamecube, Mode) => None,
                    (Gamecube, LeftThumb) => Some(&[gamecube::_grip, gamecube::_stick]),
                    (Gamecube, RightThumb) => Some(&[gamecube::_c, gamecube::_stick]),
                    (Gamecube, DPadUp) => Some(&[gamecube::_up, gamecube::_dpad]),
                    (Gamecube, DPadDown) => Some(&[gamecube::_down, gamecube::_dpad]),
                    (Gamecube, DPadLeft) => Some(&[gamecube::_left, gamecube::_dpad]),
                    (Gamecube, DPadRight) => Some(&[gamecube::_right, gamecube::_dpad]),
                    (Gamecube, Other(_)) => None,

                    (Switch, South) => Some(&[switch::_b]),
                    (Switch, East) => Some(&[switch::_a]),
                    (Switch, North) => Some(&[switch::_x]),
                    (Switch, West) => Some(&[switch::_y]),
                    (Switch, C) => None,
                    (Switch, Z) => None,
                    (Switch, LeftTrigger) => Some(&[switch::_l]),
                    (Switch, LeftTrigger2) => Some(&[switch::_zl]),
                    (Switch, RightTrigger) => Some(&[switch::_r]),
                    (Switch, RightTrigger2) => Some(&[switch::_zr]),
                    // TODO:
                    (Switch, Select) => None,
                    (Switch, Start) => None,
                    (Switch, Mode) => None,
                    (Switch, LeftThumb) => Some(&[switch::_press, switch::_l, switch::_stick]),
                    (Switch, RightThumb) => Some(&[switch::_press, switch::_r, switch::_stick]),
                    (Switch, DPadUp) => Some(&[switch::_up, switch::_dpad]),
                    (Switch, DPadDown) => Some(&[switch::_down, switch::_dpad]),
                    (Switch, DPadLeft) => Some(&[switch::_left, switch::_dpad]),
                    (Switch, DPadRight) => Some(&[switch::_right, switch::_dpad]),
                    (Switch, Other(_)) => None,

                    (Switch2, South) => Some(&[switch2::_b]),
                    (Switch2, East) => Some(&[switch2::_a]),
                    (Switch2, North) => Some(&[switch2::_x]),
                    (Switch2, West) => Some(&[switch2::_y]),
                    (Switch2, C) => None,
                    (Switch2, Z) => None,
                    (Switch2, LeftTrigger) => Some(&[switch2::_l]),
                    (Switch2, LeftTrigger2) => Some(&[switch2::_zl]),
                    (Switch2, RightTrigger) => Some(&[switch2::_r]),
                    (Switch2, RightTrigger2) => Some(&[switch2::_zr]),
                    // TODO:
                    (Switch2, Select) => None,
                    (Switch2, Start) => None,
                    (Switch2, Mode) => None,
                    (Switch2, LeftThumb) => Some(&[switch2::_press, switch2::_l, switch2::_stick]),
                    (Switch2, RightThumb) => Some(&[switch2::_press, switch2::_r, switch2::_stick]),
                    (Switch2, DPadUp) => Some(&[switch2::_up, switch2::_dpad]),
                    (Switch2, DPadDown) => Some(&[switch2::_down, switch2::_dpad]),
                    (Switch2, DPadLeft) => Some(&[switch2::_left, switch2::_dpad]),
                    (Switch2, DPadRight) => Some(&[switch2::_right, switch2::_dpad]),
                    (Switch2, Other(_)) => None,

                    (Wii, South) => Some(&[wii::_a]),
                    (Wii, East) => Some(&[wii::_b]),
                    (Wii, North) => Some(&[wii::_y]),
                    (Wii, West) => Some(&[wii::_x]),
                    (Wii, C) => None,
                    (Wii, Z) => None,
                    (Wii, LeftTrigger) => None,
                    (Wii, LeftTrigger2) => None,
                    (Wii, RightTrigger) => None,
                    (Wii, RightTrigger2) => None,
                    (Wii, Select) => None,
                    (Wii, Start) => None,
                    (Wii, Mode) => None,
                    (Wii, LeftThumb) => None,
                    (Wii, RightThumb) => None,
                    (Wii, DPadUp) => Some(&[wii::_up, wii::_dpad]),
                    (Wii, DPadDown) => Some(&[wii::_down, wii::_dpad]),
                    (Wii, DPadLeft) => Some(&[wii::_left, wii::_dpad]),
                    (Wii, DPadRight) => Some(&[wii::_right, wii::_dpad]),
                    (Wii, Other(_)) => None,

                    (WiiU, South) => Some(&[wiiu::_a]),
                    (WiiU, East) => Some(&[wiiu::_b]),
                    (WiiU, North) => Some(&[wiiu::_y]),
                    (WiiU, West) => Some(&[wiiu::_x]),
                    (WiiU, C) => None,
                    (WiiU, Z) => None,
                    (WiiU, LeftTrigger) => Some(&[wiiu::_l]),
                    (WiiU, LeftTrigger2) => Some(&[wiiu::_zl]),
                    (WiiU, RightTrigger) => Some(&[wiiu::_r]),
                    (WiiU, RightTrigger2) => Some(&[wiiu::_zr]),
                    (WiiU, Select) => Some(&[wiiu::_minus]),
                    (WiiU, Start) => Some(&[wiiu::_plus]),
                    (WiiU, Mode) => Some(&[wiiu::_home]),
                    (WiiU, LeftThumb) => None,
                    (WiiU, RightThumb) => None,
                    (WiiU, DPadUp) => Some(&[wiiu::_up, wiiu::_dpad]),
                    (WiiU, DPadDown) => Some(&[wiiu::_down, wiiu::_dpad]),
                    (WiiU, DPadLeft) => Some(&[wiiu::_left, wiiu::_dpad]),
                    (WiiU, DPadRight) => Some(&[wiiu::_right, wiiu::_dpad]),
                    (WiiU, Other(_)) => None,

                    // TODO: ps elite controller back buttons in Other
                    (PS3 | PS4 | PS5, South) => Some(&[ps::_cross]),
                    (PS3 | PS4 | PS5, East) => Some(&[ps::_circle]),
                    (PS3 | PS4 | PS5, North) => Some(&[ps::_triangle]),
                    (PS3 | PS4 | PS5, West) => Some(&[ps::_square]),
                    (PS3 | PS4 | PS5, C) => None,
                    (PS3 | PS4 | PS5, Z) => None,
                    (PS3 | PS4 | PS5, LeftTrigger) => Some(&[ps::_l1]),
                    (PS3 | PS4 | PS5, LeftTrigger2) => Some(&[ps::_l2]),
                    (PS3 | PS4 | PS5, RightTrigger) => Some(&[ps::_r1]),
                    (PS3 | PS4 | PS5, RightTrigger2) => Some(&[ps::_r2]),
                    (PS3 | PS4 | PS5, Select) => Some(&[ps::_select]),
                    (PS3 | PS4 | PS5, Start) => Some(&[ps::_start]),
                    (PS3 | PS4 | PS5, Mode) => Some(&[ps::_touchpad]),
                    (PS3 | PS4 | PS5, LeftThumb) => Some(&[ps::_press, ps::_l, ps::_stick]),
                    (PS3 | PS4 | PS5, RightThumb) => Some(&[ps::_press, ps::_r, ps::_stick]),
                    (PS3 | PS4 | PS5, DPadUp) => Some(&[ps::_up, ps::_dpad]),
                    (PS3 | PS4 | PS5, DPadDown) => Some(&[ps::_down, ps::_dpad]),
                    (PS3 | PS4 | PS5, DPadLeft) => Some(&[ps::_left, ps::_dpad]),
                    (PS3 | PS4 | PS5, DPadRight) => Some(&[ps::_right, ps::_dpad]),
                    (PS3 | PS4 | PS5, Other(_)) => None,

                    (Playdate, South) => Some(&[playdate::_a]),
                    (Playdate, East) => Some(&[playdate::_b]),
                    (Playdate, North) => None,
                    (Playdate, West) => None,
                    (Playdate, C) => None,
                    (Playdate, Z) => None,
                    (Playdate, LeftTrigger) => None,
                    (Playdate, LeftTrigger2) => None,
                    (Playdate, RightTrigger) => None,
                    (Playdate, RightTrigger2) => None,
                    (Playdate, Select) => None,
                    (Playdate, Start) => Some(&[playdate::_menu]),
                    (Playdate, Mode) => None,
                    (Playdate, LeftThumb) => None,
                    (Playdate, RightThumb) => None,
                    (Playdate, DPadUp) => Some(&[playdate::_up, playdate::_dpad]),
                    (Playdate, DPadDown) => Some(&[playdate::_down, playdate::_dpad]),
                    (Playdate, DPadLeft) => Some(&[playdate::_left, playdate::_dpad]),
                    (Playdate, DPadRight) => Some(&[playdate::_right, playdate::_dpad]),
                    (Playdate, Other(_)) => None,

                    (SteamController, South) => Some(&[steam::_a]),
                    (SteamController, East) => Some(&[steam::_b]),
                    (SteamController, North) => Some(&[steam::_y]),
                    (SteamController, West) => Some(&[steam::_x]),
                    (SteamController, C) => None,
                    (SteamController, Z) => None,
                    (SteamController, LeftTrigger) => Some(&[steam::_lb]),
                    (SteamController, LeftTrigger2) => Some(&[steam::_lt]),
                    (SteamController, RightTrigger) => Some(&[steam::_rb]),
                    (SteamController, RightTrigger2) => Some(&[steam::_rt]),
                    (SteamController, Select) => Some(&[steam::_back]),
                    (SteamController, Start) => Some(&[steam::_start]),
                    (SteamController, Mode) => None,
                    (SteamController, LeftThumb) => {
                        Some(&[steam::_press, steam::_l, steam::_stick])
                    }
                    (SteamController, RightThumb) => Some(&[steam::_pad]),
                    (SteamController, DPadUp) => Some(&[steam::_up, steam::_dpad]),
                    (SteamController, DPadDown) => Some(&[steam::_down, steam::_dpad]),
                    (SteamController, DPadLeft) => Some(&[steam::_left, steam::_dpad]),
                    (SteamController, DPadRight) => Some(&[steam::_right, steam::_dpad]),
                    (SteamController, Other(_)) => None,

                    (SteamDeck, South) => Some(&[steamdeck::_a]),
                    (SteamDeck, East) => Some(&[steamdeck::_b]),
                    (SteamDeck, North) => Some(&[steamdeck::_y]),
                    (SteamDeck, West) => Some(&[steamdeck::_x]),
                    (SteamDeck, C) => None,
                    (SteamDeck, Z) => None,
                    (SteamDeck, LeftTrigger) => Some(&[steamdeck::_l1]),
                    (SteamDeck, LeftTrigger2) => Some(&[steamdeck::_l2]),
                    (SteamDeck, RightTrigger) => Some(&[steamdeck::_r1]),
                    (SteamDeck, RightTrigger2) => Some(&[steamdeck::_r2]),
                    (SteamDeck, Select) => Some(&[steamdeck::_view]),
                    (SteamDeck, Start) => Some(&[steamdeck::_options]),
                    (SteamDeck, Mode) => None,
                    (SteamDeck, LeftThumb) => {
                        Some(&[steamdeck::_press, steamdeck::_l, steamdeck::_stick])
                    }
                    (SteamDeck, RightThumb) => {
                        Some(&[steamdeck::_press, steamdeck::_r, steamdeck::_stick])
                    }
                    (SteamDeck, DPadUp) => Some(&[steamdeck::_up, steamdeck::_dpad]),
                    (SteamDeck, DPadDown) => Some(&[steamdeck::_down, steamdeck::_dpad]),
                    (SteamDeck, DPadLeft) => Some(&[steamdeck::_left, steamdeck::_dpad]),
                    (SteamDeck, DPadRight) => Some(&[steamdeck::_right, steamdeck::_dpad]),
                    (SteamDeck, Other(_)) => None,

                    // TODO: xbox elite controller back buttons in Other
                    (Xbox, South) => Some(&[xbox::_a]),
                    (Xbox, East) => Some(&[xbox::_b]),
                    (Xbox, North) => Some(&[xbox::_y]),
                    (Xbox, West) => Some(&[xbox::_x]),
                    (Xbox, C) => None,
                    (Xbox, Z) => None,
                    (Xbox, LeftTrigger) => Some(&[xbox::_lb]),
                    (Xbox, LeftTrigger2) => Some(&[xbox::_lt]),
                    (Xbox, RightTrigger) => Some(&[xbox::_rb]),
                    (Xbox, RightTrigger2) => Some(&[xbox::_rt]),
                    (Xbox, Select) => Some(&[xbox::_menu]),
                    (Xbox, Start) => Some(&[xbox::_start]),
                    (Xbox, Mode) => Some(&[xbox::_guide]),
                    (Xbox, LeftThumb) => Some(&[xbox::_press, xbox::_l, xbox::_stick]),
                    (Xbox, RightThumb) => Some(&[xbox::_press, xbox::_r, xbox::_stick]),
                    (Xbox, DPadUp) => Some(&[xbox::_up, xbox::_dpad]),
                    (Xbox, DPadDown) => Some(&[xbox::_down, xbox::_dpad]),
                    (Xbox, DPadLeft) => Some(&[xbox::_left, xbox::_dpad]),
                    (Xbox, DPadRight) => Some(&[xbox::_right, xbox::_dpad]),
                    (Xbox, Other(_)) => None,
                }
            }
            #[cfg(feature = "use_xelu_free_controller_key_prompts")]
            #[rustfmt::skip]
            Pack::Xelu => match self {
                _ => todo!(),
            },
        }
    }
}
