use bevy_input::gamepad::GamepadButton;

#[cfg(feature = "use_kenney_input_prompts")]
use kenney_input_prompts::tokenize_dir::_kenney_input_prompts_1_4::{
    _Generic as generic, _Nintendo_Gamecube as gamecube, _Nintendo_Switch as switch, _Nintendo_Switch_2 as switch2, _Nintendo_Wii as wii, _Nintendo_WiiU as wiiu,
    _PlayStation_Series as ps, _Playdate as playdate, _Steam_Controller as steam, _Steam_Deck as steamdeck, _Xbox_Series as xbox,
};

use crate::{first_file_path, Pack, ToFile};

#[derive(Clone, Copy)]
pub enum GamepadBrand {
    Generic,
    NintendoGamecube,
    NintendoSwitch,
    NintendoSwitch2,
    NintendoWii,
    NintendoWiiU,
    PlayStationSeries,
    Playdate,
    SteamController,
    SteamDeck,
    XboxSeries,
}

impl ToFile for GamepadButton {
    type Options = GamepadBrand;

    fn file_indices<'a, 'b>(&self, pack: Pack, gamepad_brand: GamepadBrand) -> Option<&'a [&'b [usize]]> {
        match pack {
            #[cfg(feature = "use_kenney_input_prompts")]
            #[rustfmt::skip]
            Pack::Kenney => match (gamepad_brand, self) {
                (GamepadBrand::Generic, GamepadButton::South | GamepadButton::East | GamepadButton::North | GamepadButton::West) => Some(&[generic::stem_words::_button, generic::stem_words::_circle]),
                (GamepadBrand::Generic, GamepadButton::C) => None,
                (GamepadBrand::Generic, GamepadButton::Z) => None,
                (GamepadBrand::Generic, GamepadButton::LeftTrigger | GamepadButton::LeftTrigger2 | GamepadButton::RightTrigger | GamepadButton::RightTrigger2) => Some(&[generic::stem_words::_trigger]),
                (GamepadBrand::Generic, GamepadButton::Select) => None,
                (GamepadBrand::Generic, GamepadButton::Start) => None,
                (GamepadBrand::Generic, GamepadButton::Mode) => None,
                (GamepadBrand::Generic, GamepadButton::LeftThumb | GamepadButton::RightThumb) => Some(&[generic::stem_words::_side, generic::stem_words::_stick]),
                (GamepadBrand::Generic, GamepadButton::DPadUp) => None,
                (GamepadBrand::Generic, GamepadButton::DPadDown) => None,
                (GamepadBrand::Generic, GamepadButton::DPadLeft) => None,
                (GamepadBrand::Generic, GamepadButton::DPadRight) => None,
                (GamepadBrand::Generic, GamepadButton::Other(_)) => None,
    
                (GamepadBrand::NintendoGamecube, GamepadButton::South) => Some(&[gamecube::stem_words::_a]),
                (GamepadBrand::NintendoGamecube, GamepadButton::East) => Some(&[gamecube::stem_words::_b]),
                (GamepadBrand::NintendoGamecube, GamepadButton::North) => Some(&[gamecube::stem_words::_y]),
                (GamepadBrand::NintendoGamecube, GamepadButton::West) => Some(&[gamecube::stem_words::_x]),
                (GamepadBrand::NintendoGamecube, GamepadButton::C) => None,
                (GamepadBrand::NintendoGamecube, GamepadButton::Z) => None,
                (GamepadBrand::NintendoGamecube, GamepadButton::LeftTrigger) => None,
                (GamepadBrand::NintendoGamecube, GamepadButton::LeftTrigger2) => None,
                (GamepadBrand::NintendoGamecube, GamepadButton::RightTrigger) => None,
                (GamepadBrand::NintendoGamecube, GamepadButton::RightTrigger2) => None,
                (GamepadBrand::NintendoGamecube, GamepadButton::Select) => None,
                (GamepadBrand::NintendoGamecube, GamepadButton::Start) => Some(&[gamecube::stem_words::_start]),
                (GamepadBrand::NintendoGamecube, GamepadButton::Mode) => None,
                (GamepadBrand::NintendoGamecube, GamepadButton::LeftThumb) => Some(&[gamecube::stem_words::_grip, gamecube::stem_words::_stick]),
                (GamepadBrand::NintendoGamecube, GamepadButton::RightThumb) => Some(&[gamecube::stem_words::_c, gamecube::stem_words::_stick]),
                (GamepadBrand::NintendoGamecube, GamepadButton::DPadUp) => Some(&[gamecube::stem_words::_up, gamecube::stem_words::_dpad]),
                (GamepadBrand::NintendoGamecube, GamepadButton::DPadDown) => Some(&[gamecube::stem_words::_down, gamecube::stem_words::_dpad]),
                (GamepadBrand::NintendoGamecube, GamepadButton::DPadLeft) => Some(&[gamecube::stem_words::_left, gamecube::stem_words::_dpad]),
                (GamepadBrand::NintendoGamecube, GamepadButton::DPadRight) => Some(&[gamecube::stem_words::_right, gamecube::stem_words::_dpad]),
                (GamepadBrand::NintendoGamecube, GamepadButton::Other(_)) => None,
    
                (GamepadBrand::NintendoSwitch, GamepadButton::South) => Some(&[switch::stem_words::_a]),
                (GamepadBrand::NintendoSwitch, GamepadButton::East) => Some(&[switch::stem_words::_b]),
                (GamepadBrand::NintendoSwitch, GamepadButton::North) => Some(&[switch::stem_words::_y]),
                (GamepadBrand::NintendoSwitch, GamepadButton::West) => Some(&[switch::stem_words::_x]),
                (GamepadBrand::NintendoSwitch, GamepadButton::C) => None,
                (GamepadBrand::NintendoSwitch, GamepadButton::Z) => None,
                (GamepadBrand::NintendoSwitch, GamepadButton::LeftTrigger) => Some(&[switch::stem_words::_l]),
                (GamepadBrand::NintendoSwitch, GamepadButton::LeftTrigger2) => Some(&[switch::stem_words::_zl]),
                (GamepadBrand::NintendoSwitch, GamepadButton::RightTrigger) => Some(&[switch::stem_words::_r]),
                (GamepadBrand::NintendoSwitch, GamepadButton::RightTrigger2) => Some(&[switch::stem_words::_zr]),
                // TODO:
                (GamepadBrand::NintendoSwitch, GamepadButton::Select) => None,
                (GamepadBrand::NintendoSwitch, GamepadButton::Start) => None,
                (GamepadBrand::NintendoSwitch, GamepadButton::Mode) => None,
                (GamepadBrand::NintendoSwitch, GamepadButton::LeftThumb) => Some(&[switch::stem_words::_side, switch::stem_words::_l, switch::stem_words::_stick]),
                (GamepadBrand::NintendoSwitch, GamepadButton::RightThumb) => Some(&[switch::stem_words::_side, switch::stem_words::_r, switch::stem_words::_stick]),
                (GamepadBrand::NintendoSwitch, GamepadButton::DPadUp) => Some(&[switch::stem_words::_up, switch::stem_words::_dpad]),
                (GamepadBrand::NintendoSwitch, GamepadButton::DPadDown) => Some(&[switch::stem_words::_down, switch::stem_words::_dpad]),
                (GamepadBrand::NintendoSwitch, GamepadButton::DPadLeft) => Some(&[switch::stem_words::_left, switch::stem_words::_dpad]),
                (GamepadBrand::NintendoSwitch, GamepadButton::DPadRight) => Some(&[switch::stem_words::_right, switch::stem_words::_dpad]),
                (GamepadBrand::NintendoSwitch, GamepadButton::Other(_)) => None,
    
                (GamepadBrand::NintendoSwitch2, GamepadButton::South) => Some(&[switch2::stem_words::_a]),
                (GamepadBrand::NintendoSwitch2, GamepadButton::East) => Some(&[switch2::stem_words::_b]),
                (GamepadBrand::NintendoSwitch2, GamepadButton::North) => Some(&[switch2::stem_words::_y]),
                (GamepadBrand::NintendoSwitch2, GamepadButton::West) => Some(&[switch2::stem_words::_x]),
                (GamepadBrand::NintendoSwitch2, GamepadButton::C) => None,
                (GamepadBrand::NintendoSwitch2, GamepadButton::Z) => None,
                (GamepadBrand::NintendoSwitch2, GamepadButton::LeftTrigger) => Some(&[switch2::stem_words::_l]),
                (GamepadBrand::NintendoSwitch2, GamepadButton::LeftTrigger2) => Some(&[switch2::stem_words::_zl]),
                (GamepadBrand::NintendoSwitch2, GamepadButton::RightTrigger) => Some(&[switch2::stem_words::_r]),
                (GamepadBrand::NintendoSwitch2, GamepadButton::RightTrigger2) => Some(&[switch2::stem_words::_zr]),
                // TODO:
                (GamepadBrand::NintendoSwitch2, GamepadButton::Select) => None,
                (GamepadBrand::NintendoSwitch2, GamepadButton::Start) => None,
                (GamepadBrand::NintendoSwitch2, GamepadButton::Mode) => None,
                (GamepadBrand::NintendoSwitch2, GamepadButton::LeftThumb) => Some(&[switch2::stem_words::_side, switch2::stem_words::_l, switch2::stem_words::_stick]),
                (GamepadBrand::NintendoSwitch2, GamepadButton::RightThumb) => Some(&[switch2::stem_words::_side, switch2::stem_words::_r, switch2::stem_words::_stick]),
                (GamepadBrand::NintendoSwitch2, GamepadButton::DPadUp) => Some(&[switch2::stem_words::_up, switch2::stem_words::_dpad]),
                (GamepadBrand::NintendoSwitch2, GamepadButton::DPadDown) => Some(&[switch2::stem_words::_down, switch2::stem_words::_dpad]),
                (GamepadBrand::NintendoSwitch2, GamepadButton::DPadLeft) => Some(&[switch2::stem_words::_left, switch2::stem_words::_dpad]),
                (GamepadBrand::NintendoSwitch2, GamepadButton::DPadRight) => Some(&[switch2::stem_words::_right, switch2::stem_words::_dpad]),
                (GamepadBrand::NintendoSwitch2, GamepadButton::Other(_)) => None,
    
                (GamepadBrand::NintendoWii, GamepadButton::South) => Some(&[wii::stem_words::_a]),
                (GamepadBrand::NintendoWii, GamepadButton::East) => Some(&[wii::stem_words::_b]),
                (GamepadBrand::NintendoWii, GamepadButton::North) => Some(&[wii::stem_words::_y]),
                (GamepadBrand::NintendoWii, GamepadButton::West) => Some(&[wii::stem_words::_x]),
                (GamepadBrand::NintendoWii, GamepadButton::C) => None,
                (GamepadBrand::NintendoWii, GamepadButton::Z) => None,
                (GamepadBrand::NintendoWii, GamepadButton::LeftTrigger) => None,
                (GamepadBrand::NintendoWii, GamepadButton::LeftTrigger2) => None,
                (GamepadBrand::NintendoWii, GamepadButton::RightTrigger) => None,
                (GamepadBrand::NintendoWii, GamepadButton::RightTrigger2) => None,
                (GamepadBrand::NintendoWii, GamepadButton::Select) => None,
                (GamepadBrand::NintendoWii, GamepadButton::Start) => None,
                (GamepadBrand::NintendoWii, GamepadButton::Mode) => None,
                (GamepadBrand::NintendoWii, GamepadButton::LeftThumb) => None,
                (GamepadBrand::NintendoWii, GamepadButton::RightThumb) => None,
                (GamepadBrand::NintendoWii, GamepadButton::DPadUp) => Some(&[wii::stem_words::_up, wii::stem_words::_dpad]),
                (GamepadBrand::NintendoWii, GamepadButton::DPadDown) => Some(&[wii::stem_words::_down, wii::stem_words::_dpad]),
                (GamepadBrand::NintendoWii, GamepadButton::DPadLeft) => Some(&[wii::stem_words::_left, wii::stem_words::_dpad]),
                (GamepadBrand::NintendoWii, GamepadButton::DPadRight) => Some(&[wii::stem_words::_right, wii::stem_words::_dpad]),
                (GamepadBrand::NintendoWii, GamepadButton::Other(_)) => None,
    
                (GamepadBrand::NintendoWiiU, GamepadButton::South) => Some(&[wiiu::stem_words::_a]),
                (GamepadBrand::NintendoWiiU, GamepadButton::East) => Some(&[wiiu::stem_words::_b]),
                (GamepadBrand::NintendoWiiU, GamepadButton::North) => Some(&[wiiu::stem_words::_y]),
                (GamepadBrand::NintendoWiiU, GamepadButton::West) => Some(&[wiiu::stem_words::_x]),
                (GamepadBrand::NintendoWiiU, GamepadButton::C) => None,
                (GamepadBrand::NintendoWiiU, GamepadButton::Z) => None,
                (GamepadBrand::NintendoWiiU, GamepadButton::LeftTrigger) => Some(&[wiiu::stem_words::_l]),
                (GamepadBrand::NintendoWiiU, GamepadButton::LeftTrigger2) => Some(&[wiiu::stem_words::_zl]),
                (GamepadBrand::NintendoWiiU, GamepadButton::RightTrigger) => Some(&[wiiu::stem_words::_r]),
                (GamepadBrand::NintendoWiiU, GamepadButton::RightTrigger2) => Some(&[wiiu::stem_words::_zr]),
                (GamepadBrand::NintendoWiiU, GamepadButton::Select) => Some(&[wiiu::stem_words::_minus]),
                (GamepadBrand::NintendoWiiU, GamepadButton::Start) => Some(&[wiiu::stem_words::_plus]),
                (GamepadBrand::NintendoWiiU, GamepadButton::Mode) => Some(&[wiiu::stem_words::_home]),
                (GamepadBrand::NintendoWiiU, GamepadButton::LeftThumb) => None,
                (GamepadBrand::NintendoWiiU, GamepadButton::RightThumb) => None,
                (GamepadBrand::NintendoWiiU, GamepadButton::DPadUp) => Some(&[wiiu::stem_words::_up, wiiu::stem_words::_dpad]),
                (GamepadBrand::NintendoWiiU, GamepadButton::DPadDown) => Some(&[wiiu::stem_words::_down, wiiu::stem_words::_dpad]),
                (GamepadBrand::NintendoWiiU, GamepadButton::DPadLeft) => Some(&[wiiu::stem_words::_left, wiiu::stem_words::_dpad]),
                (GamepadBrand::NintendoWiiU, GamepadButton::DPadRight) => Some(&[wiiu::stem_words::_right, wiiu::stem_words::_dpad]),
                (GamepadBrand::NintendoWiiU, GamepadButton::Other(_)) => None,
    
                (GamepadBrand::PlayStationSeries, GamepadButton::South) => Some(&[ps::stem_words::_cross]),
                (GamepadBrand::PlayStationSeries, GamepadButton::East) => Some(&[ps::stem_words::_circle]),
                (GamepadBrand::PlayStationSeries, GamepadButton::North) => Some(&[ps::stem_words::_triangle]),
                (GamepadBrand::PlayStationSeries, GamepadButton::West) => Some(&[ps::stem_words::_square]),
                (GamepadBrand::PlayStationSeries, GamepadButton::C) => None,
                (GamepadBrand::PlayStationSeries, GamepadButton::Z) => None,
                (GamepadBrand::PlayStationSeries, GamepadButton::LeftTrigger) => Some(&[ps::stem_words::_l1]),
                (GamepadBrand::PlayStationSeries, GamepadButton::LeftTrigger2) => Some(&[ps::stem_words::_l2]),
                (GamepadBrand::PlayStationSeries, GamepadButton::RightTrigger) => Some(&[ps::stem_words::_r1]),
                (GamepadBrand::PlayStationSeries, GamepadButton::RightTrigger2) => Some(&[ps::stem_words::_r2]),
                (GamepadBrand::PlayStationSeries, GamepadButton::Select) => Some(&[ps::stem_words::_select]),
                (GamepadBrand::PlayStationSeries, GamepadButton::Start) => Some(&[ps::stem_words::_start]),
                (GamepadBrand::PlayStationSeries, GamepadButton::Mode) => Some(&[ps::stem_words::_touchpad]),
                (GamepadBrand::PlayStationSeries, GamepadButton::LeftThumb) => Some(&[ps::stem_words::_side, ps::stem_words::_l, ps::stem_words::_stick]),
                (GamepadBrand::PlayStationSeries, GamepadButton::RightThumb) => Some(&[ps::stem_words::_side, ps::stem_words::_r, ps::stem_words::_stick]),
                (GamepadBrand::PlayStationSeries, GamepadButton::DPadUp) => Some(&[ps::stem_words::_up, ps::stem_words::_dpad]),
                (GamepadBrand::PlayStationSeries, GamepadButton::DPadDown) => Some(&[ps::stem_words::_down, ps::stem_words::_dpad]),
                (GamepadBrand::PlayStationSeries, GamepadButton::DPadLeft) => Some(&[ps::stem_words::_left, ps::stem_words::_dpad]),
                (GamepadBrand::PlayStationSeries, GamepadButton::DPadRight) => Some(&[ps::stem_words::_right, ps::stem_words::_dpad]),
                (GamepadBrand::PlayStationSeries, GamepadButton::Other(_)) => None,
    
                (GamepadBrand::Playdate, GamepadButton::South) => Some(&[playdate::stem_words::_a]),
                (GamepadBrand::Playdate, GamepadButton::East) => Some(&[playdate::stem_words::_b]),
                (GamepadBrand::Playdate, GamepadButton::North) => None,
                (GamepadBrand::Playdate, GamepadButton::West) => None,
                (GamepadBrand::Playdate, GamepadButton::C) => None,
                (GamepadBrand::Playdate, GamepadButton::Z) => None,
                (GamepadBrand::Playdate, GamepadButton::LeftTrigger) => None,
                (GamepadBrand::Playdate, GamepadButton::LeftTrigger2) => None,
                (GamepadBrand::Playdate, GamepadButton::RightTrigger) => None,
                (GamepadBrand::Playdate, GamepadButton::RightTrigger2) => None,
                (GamepadBrand::Playdate, GamepadButton::Select) => None,
                (GamepadBrand::Playdate, GamepadButton::Start) => Some(&[playdate::stem_words::_menu]),
                (GamepadBrand::Playdate, GamepadButton::Mode) => None,
                (GamepadBrand::Playdate, GamepadButton::LeftThumb) => None,
                (GamepadBrand::Playdate, GamepadButton::RightThumb) => None,
                (GamepadBrand::Playdate, GamepadButton::DPadUp) => Some(&[playdate::stem_words::_up, playdate::stem_words::_dpad]),
                (GamepadBrand::Playdate, GamepadButton::DPadDown) => Some(&[playdate::stem_words::_down, playdate::stem_words::_dpad]),
                (GamepadBrand::Playdate, GamepadButton::DPadLeft) => Some(&[playdate::stem_words::_left, playdate::stem_words::_dpad]),
                (GamepadBrand::Playdate, GamepadButton::DPadRight) => Some(&[playdate::stem_words::_right, playdate::stem_words::_dpad]),
                (GamepadBrand::Playdate, GamepadButton::Other(_)) => None,
    
                (GamepadBrand::SteamController, GamepadButton::South) => Some(&[steam::stem_words::_a]),
                (GamepadBrand::SteamController, GamepadButton::East) => Some(&[steam::stem_words::_b]),
                (GamepadBrand::SteamController, GamepadButton::North) => Some(&[steam::stem_words::_y]),
                (GamepadBrand::SteamController, GamepadButton::West) => Some(&[steam::stem_words::_x]),
                (GamepadBrand::SteamController, GamepadButton::C) => None,
                (GamepadBrand::SteamController, GamepadButton::Z) => None,
                (GamepadBrand::SteamController, GamepadButton::LeftTrigger) => Some(&[steam::stem_words::_lb]),
                (GamepadBrand::SteamController, GamepadButton::LeftTrigger2) => Some(&[steam::stem_words::_lt]),
                (GamepadBrand::SteamController, GamepadButton::RightTrigger) => Some(&[steam::stem_words::_rb]),
                (GamepadBrand::SteamController, GamepadButton::RightTrigger2) => Some(&[steam::stem_words::_rt]),
                (GamepadBrand::SteamController, GamepadButton::Select) => Some(&[steam::stem_words::_back]),
                (GamepadBrand::SteamController, GamepadButton::Start) => Some(&[steam::stem_words::_start]),
                (GamepadBrand::SteamController, GamepadButton::Mode) => None,
                (GamepadBrand::SteamController, GamepadButton::LeftThumb) => Some(&[steam::stem_words::_side, steam::stem_words::_l, steam::stem_words::_stick]),
                (GamepadBrand::SteamController, GamepadButton::RightThumb) => Some(&[steam::stem_words::_pad]),
                (GamepadBrand::SteamController, GamepadButton::DPadUp) => Some(&[steam::stem_words::_up, steam::stem_words::_dpad]),
                (GamepadBrand::SteamController, GamepadButton::DPadDown) => Some(&[steam::stem_words::_down, steam::stem_words::_dpad]),
                (GamepadBrand::SteamController, GamepadButton::DPadLeft) => Some(&[steam::stem_words::_left, steam::stem_words::_dpad]),
                (GamepadBrand::SteamController, GamepadButton::DPadRight) => Some(&[steam::stem_words::_right, steam::stem_words::_dpad]),
                (GamepadBrand::SteamController, GamepadButton::Other(_)) => None,
    
                (GamepadBrand::SteamDeck, GamepadButton::South) => Some(&[steamdeck::stem_words::_a]),
                (GamepadBrand::SteamDeck, GamepadButton::East) => Some(&[steamdeck::stem_words::_b]),
                (GamepadBrand::SteamDeck, GamepadButton::North) => Some(&[steamdeck::stem_words::_y]),
                (GamepadBrand::SteamDeck, GamepadButton::West) => Some(&[steamdeck::stem_words::_x]),
                (GamepadBrand::SteamDeck, GamepadButton::C) => None,
                (GamepadBrand::SteamDeck, GamepadButton::Z) => None,
                (GamepadBrand::SteamDeck, GamepadButton::LeftTrigger) => Some(&[steamdeck::stem_words::_l1]),
                (GamepadBrand::SteamDeck, GamepadButton::LeftTrigger2) => Some(&[steamdeck::stem_words::_l2]),
                (GamepadBrand::SteamDeck, GamepadButton::RightTrigger) => Some(&[steamdeck::stem_words::_r1]),
                (GamepadBrand::SteamDeck, GamepadButton::RightTrigger2) => Some(&[steamdeck::stem_words::_r2]),
                (GamepadBrand::SteamDeck, GamepadButton::Select) => Some(&[steamdeck::stem_words::_view]),
                (GamepadBrand::SteamDeck, GamepadButton::Start) => Some(&[steamdeck::stem_words::_options]),
                (GamepadBrand::SteamDeck, GamepadButton::Mode) => None,
                (GamepadBrand::SteamDeck, GamepadButton::LeftThumb) => Some(&[steamdeck::stem_words::_side, steamdeck::stem_words::_l, steamdeck::stem_words::_stick]),
                (GamepadBrand::SteamDeck, GamepadButton::RightThumb) => Some(&[steamdeck::stem_words::_side, steamdeck::stem_words::_r, steamdeck::stem_words::_stick]),
                (GamepadBrand::SteamDeck, GamepadButton::DPadUp) => Some(&[steamdeck::stem_words::_up, steamdeck::stem_words::_dpad]),
                (GamepadBrand::SteamDeck, GamepadButton::DPadDown) => Some(&[steamdeck::stem_words::_down, steamdeck::stem_words::_dpad]),
                (GamepadBrand::SteamDeck, GamepadButton::DPadLeft) => Some(&[steamdeck::stem_words::_left, steamdeck::stem_words::_dpad]),
                (GamepadBrand::SteamDeck, GamepadButton::DPadRight) => Some(&[steamdeck::stem_words::_right, steamdeck::stem_words::_dpad]),
                (GamepadBrand::SteamDeck, GamepadButton::Other(_)) => None,
    
                (GamepadBrand::XboxSeries, GamepadButton::South) => Some(&[xbox::stem_words::_a]),
                (GamepadBrand::XboxSeries, GamepadButton::East) => Some(&[xbox::stem_words::_b]),
                (GamepadBrand::XboxSeries, GamepadButton::North) => Some(&[xbox::stem_words::_y]),
                (GamepadBrand::XboxSeries, GamepadButton::West) => Some(&[xbox::stem_words::_x]),
                (GamepadBrand::XboxSeries, GamepadButton::C) => None,
                (GamepadBrand::XboxSeries, GamepadButton::Z) => None,
                (GamepadBrand::XboxSeries, GamepadButton::LeftTrigger) => Some(&[xbox::stem_words::_lb]),
                (GamepadBrand::XboxSeries, GamepadButton::LeftTrigger2) => Some(&[xbox::stem_words::_lt]),
                (GamepadBrand::XboxSeries, GamepadButton::RightTrigger) => Some(&[xbox::stem_words::_rb]),
                (GamepadBrand::XboxSeries, GamepadButton::RightTrigger2) => Some(&[xbox::stem_words::_rt]),
                (GamepadBrand::XboxSeries, GamepadButton::Select) => Some(&[xbox::stem_words::_menu]),
                (GamepadBrand::XboxSeries, GamepadButton::Start) => Some(&[xbox::stem_words::_start]),
                (GamepadBrand::XboxSeries, GamepadButton::Mode) => Some(&[xbox::stem_words::_guide]),
                (GamepadBrand::XboxSeries, GamepadButton::LeftThumb) => Some(&[xbox::stem_words::_side, xbox::stem_words::_l, xbox::stem_words::_stick]),
                (GamepadBrand::XboxSeries, GamepadButton::RightThumb) => Some(&[xbox::stem_words::_side, xbox::stem_words::_r, xbox::stem_words::_stick]),
                (GamepadBrand::XboxSeries, GamepadButton::DPadUp) => Some(&[xbox::stem_words::_up, xbox::stem_words::_dpad]),
                (GamepadBrand::XboxSeries, GamepadButton::DPadDown) => Some(&[xbox::stem_words::_down, xbox::stem_words::_dpad]),
                (GamepadBrand::XboxSeries, GamepadButton::DPadLeft) => Some(&[xbox::stem_words::_left, xbox::stem_words::_dpad]),
                (GamepadBrand::XboxSeries, GamepadButton::DPadRight) => Some(&[xbox::stem_words::_right, xbox::stem_words::_dpad]),
                (GamepadBrand::XboxSeries, GamepadButton::Other(_)) => None,
            },
        }
    }
}

// pub fn gamepad_button_file_path(pack: Pack, gamepad_button: GamepadButton, gamepad_brand: GamepadBrand, extras: &[&[usize]]) -> Option<String> {
//     first_file_path(pack, [gamepad_button_file_indices(pack, gamepad_button, gamepad_brand)?, extras])
// }

// pub fn gamepad_button_file_indices<'a, 'b>(version: Pack, gamepad_button: GamepadButton, gamepad_brand: GamepadBrand) -> Option<&'a [&'b [usize]]> {
    
// }
