use bevy_input::gamepad::GamepadButton;
#[cfg(feature = "use_kenney_input_prompts")]
use kenney_input_prompts::tokenize_dir::_kenney_input_prompts_1_4 as k;

use crate::Pack;

pub enum GamepadBrand {
    Generic,
    NintendoGamecube,
    NintendoSwitch,
    NintendoSwitch2,
    NintendoWii,
    NintendoWiiU,
    PlayStationSeries,
    Playdate,
    SteamController,
    SteamDeck,
    XboxSeries,
}

impl GamepadBrand {
    pub fn to_const(&self) -> &[usize] {
        match self {
            Self::Generic => k::_Generic::DIR,
            Self::NintendoGamecube => k::_Nintendo_Gamecube::DIR,
            Self::NintendoSwitch => k::_Nintendo_Switch::DIR,
            Self::NintendoSwitch2 => k::_Nintendo_Switch_2::DIR,
            Self::NintendoWii => k::_Nintendo_Wii::DIR,
            Self::NintendoWiiU => k::_Nintendo_WiiU::DIR,
            Self::PlayStationSeries => k::_PlayStation_Series::DIR,
            Self::Playdate => k::_Playdate::DIR,
            Self::SteamController => k::_Steam_Controller::DIR,
            Self::SteamDeck => k::_Steam_Deck::DIR,
            Self::XboxSeries => k::DIR,
        }
    }
}

pub fn from_gamepad_button<'a, 'b>(version: Pack, gamepad_button: GamepadButton, gamepad_brand: GamepadBrand) -> Option<&'a [&'b [usize]]> {
    match version {
        #[cfg(feature = "use_kenney_input_prompts")]
        Pack::Kenney => match (gamepad_brand, gamepad_button) {
            (GamepadBrand::Generic, GamepadButton::South | GamepadButton::East | GamepadButton::North | GamepadButton::West) => Some(&[k::stem_words::_button, k::stem_words::_circle]),
            (GamepadBrand::Generic, GamepadButton::C) => None,
            (GamepadBrand::Generic, GamepadButton::Z) => None,
            (GamepadBrand::Generic, GamepadButton::LeftTrigger | GamepadButton::LeftTrigger2 | GamepadButton::RightTrigger | GamepadButton::RightTrigger2) => Some(&[k::stem_words::_trigger]),
            (GamepadBrand::Generic, GamepadButton::Select) => None,
            (GamepadBrand::Generic, GamepadButton::Start) => None,
            (GamepadBrand::Generic, GamepadButton::Mode) => None,
            (GamepadBrand::Generic, GamepadButton::LeftThumb | GamepadButton::RightThumb) => Some(&[k::stem_words::_side, k::stem_words::_stick]),
            (GamepadBrand::Generic, GamepadButton::DPadUp) => None,
            (GamepadBrand::Generic, GamepadButton::DPadDown) => None,
            (GamepadBrand::Generic, GamepadButton::DPadLeft) => None,
            (GamepadBrand::Generic, GamepadButton::DPadRight) => None,

            (GamepadBrand::Generic, GamepadButton::Other(_)) => None,
            (GamepadBrand::NintendoGamecube, GamepadButton::C) => None,
            (GamepadBrand::NintendoGamecube, GamepadButton::Z) => None,
            (GamepadBrand::NintendoGamecube, GamepadButton::LeftTrigger) => None,
            (GamepadBrand::NintendoGamecube, GamepadButton::LeftTrigger2) => None,
            (GamepadBrand::NintendoGamecube, GamepadButton::RightTrigger) => None,
            (GamepadBrand::NintendoGamecube, GamepadButton::RightTrigger2) => None,
            (GamepadBrand::NintendoGamecube, GamepadButton::Select) => None,
            (GamepadBrand::NintendoGamecube, GamepadButton::Start) => Some(&[k::stem_words::_start]),
            (GamepadBrand::NintendoGamecube, GamepadButton::Mode) => None,
            (GamepadBrand::NintendoGamecube, GamepadButton::LeftThumb) => Some(&[k::_Nintendo_Gamecube::stem_words::_grip, k::stem_words::_stick]),
            (GamepadBrand::NintendoGamecube, GamepadButton::RightThumb) => Some(&[k::stem_words::_c, k::stem_words::_stick]),
            (GamepadBrand::NintendoGamecube, GamepadButton::Other(_)) => None,

            (GamepadBrand::NintendoSwitch | GamepadBrand::NintendoSwitch2, GamepadButton::C) => None,
            (GamepadBrand::NintendoSwitch | GamepadBrand::NintendoSwitch2, GamepadButton::Z) => None,
            (GamepadBrand::NintendoSwitch | GamepadBrand::NintendoSwitch2, GamepadButton::LeftTrigger) => Some(&[k::stem_words::_l]),
            (GamepadBrand::NintendoSwitch | GamepadBrand::NintendoSwitch2, GamepadButton::LeftTrigger2) => Some(&[k::stem_words::_zl]),
            (GamepadBrand::NintendoSwitch | GamepadBrand::NintendoSwitch2, GamepadButton::RightTrigger) => Some(&[k::stem_words::_r]),
            (GamepadBrand::NintendoSwitch | GamepadBrand::NintendoSwitch2, GamepadButton::RightTrigger2) => Some(&[k::stem_words::_zr]),
            // TODO:
            (GamepadBrand::NintendoSwitch | GamepadBrand::NintendoSwitch2, GamepadButton::Select) =>None,
            (GamepadBrand::NintendoSwitch | GamepadBrand::NintendoSwitch2, GamepadButton::Start) => None,
            (GamepadBrand::NintendoSwitch | GamepadBrand::NintendoSwitch2, GamepadButton::Mode) => None,
            (GamepadBrand::NintendoSwitch | GamepadBrand::NintendoSwitch2, GamepadButton::LeftThumb) => Some(&[k::stem_words::_side, k::stem_words::_l, k::stem_words::_stick]),
            (GamepadBrand::NintendoSwitch | GamepadBrand::NintendoSwitch2, GamepadButton::RightThumb) => Some(&[k::stem_words::_side, k::stem_words::_r, k::stem_words::_stick]),
            (GamepadBrand::NintendoSwitch | GamepadBrand::NintendoSwitch2, GamepadButton::Other(_)) => None,

            (GamepadBrand::NintendoWii, GamepadButton::C) => None,
            (GamepadBrand::NintendoWii, GamepadButton::Z) => None,
            (GamepadBrand::NintendoWii, GamepadButton::LeftTrigger) => None,
            (GamepadBrand::NintendoWii, GamepadButton::LeftTrigger2) => None,
            (GamepadBrand::NintendoWii, GamepadButton::RightTrigger) => None,
            (GamepadBrand::NintendoWii, GamepadButton::RightTrigger2) => None,
            (GamepadBrand::NintendoWii, GamepadButton::Select) => None,
            (GamepadBrand::NintendoWii, GamepadButton::Start) => None,
            (GamepadBrand::NintendoWii, GamepadButton::Mode) => None,
            (GamepadBrand::NintendoWii, GamepadButton::LeftThumb) => None,
            (GamepadBrand::NintendoWii, GamepadButton::RightThumb) => None,
            (GamepadBrand::NintendoWii, GamepadButton::Other(_)) => None,

            (GamepadBrand::NintendoWiiU, GamepadButton::C) => None,
            (GamepadBrand::NintendoWiiU, GamepadButton::Z) => None,
            (GamepadBrand::NintendoWiiU, GamepadButton::LeftTrigger) => Some(&[k::stem_words::_l]),
            (GamepadBrand::NintendoWiiU, GamepadButton::LeftTrigger2) => Some(&[k::stem_words::_zl]),
            (GamepadBrand::NintendoWiiU, GamepadButton::RightTrigger) => Some(&[k::stem_words::_r]),
            (GamepadBrand::NintendoWiiU, GamepadButton::RightTrigger2) => Some(&[k::stem_words::_zr]),
            (GamepadBrand::NintendoWiiU, GamepadButton::Select) => Some(&[k::stem_words::_minus]),
            (GamepadBrand::NintendoWiiU, GamepadButton::Start) => Some(&[k::stem_words::_plus]),
            (GamepadBrand::NintendoWiiU, GamepadButton::Mode) => Some(&[k::stem_words::_home]),
            (GamepadBrand::NintendoWiiU, GamepadButton::LeftThumb) => None,
            (GamepadBrand::NintendoWiiU, GamepadButton::RightThumb) => None,
            (GamepadBrand::NintendoWiiU, GamepadButton::Other(_)) => None,

            (GamepadBrand::PlayStationSeries, GamepadButton::South) => Some(&[k::stem_words::_cross]),
            (GamepadBrand::PlayStationSeries, GamepadButton::East) => Some(&[k::stem_words::_circle]),
            (GamepadBrand::PlayStationSeries, GamepadButton::North) => Some(&[k::_PlayStation_Series::stem_words::_triangle]),
            (GamepadBrand::PlayStationSeries, GamepadButton::West) => Some(&[k::stem_words::_square]),
            (GamepadBrand::PlayStationSeries, GamepadButton::C) => None,
            (GamepadBrand::PlayStationSeries, GamepadButton::Z) => None,
            (GamepadBrand::PlayStationSeries, GamepadButton::LeftTrigger) => Some(&[k::stem_words::_l1]),
            (GamepadBrand::PlayStationSeries, GamepadButton::LeftTrigger2) => Some(&[k::stem_words::_l2]),
            (GamepadBrand::PlayStationSeries, GamepadButton::RightTrigger) => Some(&[k::stem_words::_r1]),
            (GamepadBrand::PlayStationSeries, GamepadButton::RightTrigger2) => Some(&[k::stem_words::_r2]),
            (GamepadBrand::PlayStationSeries, GamepadButton::Select) => Some(&[k::_PlayStation_Series::stem_words::_select]),
            (GamepadBrand::PlayStationSeries, GamepadButton::Start) => Some(&[k::stem_words::_start]),
            (GamepadBrand::PlayStationSeries, GamepadButton::Mode) => Some(&[k::_PlayStation_Series::stem_words::_touchpad]),
            (GamepadBrand::PlayStationSeries, GamepadButton::LeftThumb) => Some(&[k::stem_words::_side, k::stem_words::_l, k::stem_words::_stick]),
            (GamepadBrand::PlayStationSeries, GamepadButton::RightThumb) => Some(&[k::stem_words::_side, k::stem_words::_r, k::stem_words::_stick]),
            (GamepadBrand::PlayStationSeries, GamepadButton::Other(_)) => None,

            (GamepadBrand::Playdate, GamepadButton::C) => None,
            (GamepadBrand::Playdate, GamepadButton::Z) => None,
            (GamepadBrand::Playdate, GamepadButton::LeftTrigger) => None,
            (GamepadBrand::Playdate, GamepadButton::LeftTrigger2) => None,
            (GamepadBrand::Playdate, GamepadButton::RightTrigger) => None,
            (GamepadBrand::Playdate, GamepadButton::RightTrigger2) => None,
            (GamepadBrand::Playdate, GamepadButton::Select) => None,
            (GamepadBrand::Playdate, GamepadButton::Start) => Some(&[k::stem_words::_menu]),
            (GamepadBrand::Playdate, GamepadButton::Mode) => None,
            (GamepadBrand::Playdate, GamepadButton::LeftThumb) => None,
            (GamepadBrand::Playdate, GamepadButton::RightThumb) => None,
            (GamepadBrand::Playdate, GamepadButton::Other(_)) => None,

            (GamepadBrand::SteamController, GamepadButton::C) => None,
            (GamepadBrand::SteamController, GamepadButton::Z) => None,
            (GamepadBrand::SteamController, GamepadButton::Select) => Some(&[k::stem_words::_back]),
            (GamepadBrand::SteamController, GamepadButton::Start) => Some(&[k::stem_words::_start]),
            (GamepadBrand::SteamController, GamepadButton::Mode) => None,
            (GamepadBrand::SteamController, GamepadButton::LeftThumb) => Some(&[k::stem_words::_side, k::stem_words::_l, k::stem_words::_stick]),
            (GamepadBrand::SteamController, GamepadButton::RightThumb) => Some(&[k::_Steam_Controller::stem_words::_pad]),
            (GamepadBrand::SteamController, GamepadButton::Other(_)) => None,

            (GamepadBrand::SteamDeck, GamepadButton::C) => None,
            (GamepadBrand::SteamDeck, GamepadButton::Z) => None,
            (GamepadBrand::SteamDeck, GamepadButton::LeftTrigger) => Some(&[k::stem_words::_l1]),
            (GamepadBrand::SteamDeck, GamepadButton::LeftTrigger2) => Some(&[k::stem_words::_l2]),
            (GamepadBrand::SteamDeck, GamepadButton::RightTrigger) => Some(&[k::stem_words::_r1]),
            (GamepadBrand::SteamDeck, GamepadButton::RightTrigger2) => Some(&[k::stem_words::_r2]),
            (GamepadBrand::SteamDeck, GamepadButton::Select) => Some(&[k::stem_words::_view]),
            (GamepadBrand::SteamDeck, GamepadButton::Start) => Some(&[k::stem_words::_options]),
            (GamepadBrand::SteamDeck, GamepadButton::Mode) => None,
            (GamepadBrand::SteamDeck, GamepadButton::LeftThumb) => Some(&[k::stem_words::_side, k::stem_words::_l, k::stem_words::_stick]),
            (GamepadBrand::SteamDeck, GamepadButton::RightThumb) => Some(&[k::stem_words::_side, k::stem_words::_r, k::stem_words::_stick]),
            (GamepadBrand::SteamDeck, GamepadButton::Other(_)) => None,

            (GamepadBrand::XboxSeries | GamepadBrand::NintendoWii | GamepadBrand::NintendoWiiU | GamepadBrand::SteamController | GamepadBrand::NintendoSwitch | GamepadBrand::NintendoSwitch2 | GamepadBrand::NintendoGamecube | GamepadBrand::Playdate | GamepadBrand::SteamDeck, GamepadButton::South) => Some(&[k::stem_words::_a]),
            (GamepadBrand::XboxSeries | GamepadBrand::NintendoWii | GamepadBrand::NintendoWiiU | GamepadBrand::SteamController | GamepadBrand::NintendoSwitch | GamepadBrand::NintendoSwitch2 | GamepadBrand::NintendoGamecube | GamepadBrand::Playdate | GamepadBrand::SteamDeck, GamepadButton::East) => Some(&[k::stem_words::_b]),
            (GamepadBrand::XboxSeries | GamepadBrand::NintendoWii | GamepadBrand::NintendoWiiU | GamepadBrand::SteamController | GamepadBrand::NintendoSwitch | GamepadBrand::NintendoSwitch2 | GamepadBrand::NintendoGamecube | GamepadBrand::Playdate | GamepadBrand::SteamDeck, GamepadButton::North) => Some(&[k::stem_words::_y]),
            (GamepadBrand::XboxSeries | GamepadBrand::NintendoWii | GamepadBrand::NintendoWiiU | GamepadBrand::SteamController | GamepadBrand::NintendoSwitch | GamepadBrand::NintendoSwitch2 | GamepadBrand::NintendoGamecube | GamepadBrand::Playdate | GamepadBrand::SteamDeck, GamepadButton::West) => Some(&[k::stem_words::_x]),
            (GamepadBrand::XboxSeries, GamepadButton::C) => None,
            (GamepadBrand::XboxSeries, GamepadButton::Z) => None,
            (GamepadBrand::XboxSeries | GamepadBrand::SteamController, GamepadButton::LeftTrigger) => Some(&[k::stem_words::_lb]),
            (GamepadBrand::XboxSeries | GamepadBrand::SteamController, GamepadButton::LeftTrigger2) => Some(&[k::stem_words::_lt]),
            (GamepadBrand::XboxSeries | GamepadBrand::SteamController, GamepadButton::RightTrigger) => Some(&[k::stem_words::_rb]),
            (GamepadBrand::XboxSeries | GamepadBrand::SteamController, GamepadButton::RightTrigger2) => Some(&[k::stem_words::_rt]),
            (GamepadBrand::XboxSeries, GamepadButton::Select) => Some(&[k::stem_words::_menu]),
            (GamepadBrand::XboxSeries, GamepadButton::Start) => Some(&[k::stem_words::_start]),
            (GamepadBrand::XboxSeries, GamepadButton::Mode) => Some(&[k::stem_words::_guide]),
            (GamepadBrand::XboxSeries, GamepadButton::LeftThumb) => Some(&[k::stem_words::_side, k::stem_words::_l, k::stem_words::_stick]),
            (GamepadBrand::XboxSeries, GamepadButton::RightThumb) => Some(&[k::stem_words::_side, k::stem_words::_r, k::stem_words::_stick]),
            (GamepadBrand::XboxSeries | GamepadBrand::NintendoWii | GamepadBrand::NintendoWiiU | GamepadBrand::SteamController | GamepadBrand::NintendoSwitch | GamepadBrand::NintendoSwitch2 | GamepadBrand::NintendoGamecube | GamepadBrand::Playdate | GamepadBrand::SteamDeck | GamepadBrand::PlayStationSeries, GamepadButton::DPadUp) => Some(&[k::stem_words::_dpad, k::stem_words::_up]),
            (GamepadBrand::XboxSeries | GamepadBrand::NintendoWii | GamepadBrand::NintendoWiiU | GamepadBrand::SteamController | GamepadBrand::NintendoSwitch | GamepadBrand::NintendoSwitch2 | GamepadBrand::NintendoGamecube | GamepadBrand::Playdate | GamepadBrand::SteamDeck | GamepadBrand::PlayStationSeries, GamepadButton::DPadDown) => Some(&[k::stem_words::_dpad, k::stem_words::_down]),
            (GamepadBrand::XboxSeries | GamepadBrand::NintendoWii | GamepadBrand::NintendoWiiU | GamepadBrand::SteamController | GamepadBrand::NintendoSwitch | GamepadBrand::NintendoSwitch2 | GamepadBrand::NintendoGamecube | GamepadBrand::Playdate | GamepadBrand::SteamDeck | GamepadBrand::PlayStationSeries, GamepadButton::DPadLeft) => Some(&[k::stem_words::_dpad, k::stem_words::_left]),
            (GamepadBrand::XboxSeries | GamepadBrand::NintendoWii | GamepadBrand::NintendoWiiU | GamepadBrand::SteamController | GamepadBrand::NintendoSwitch | GamepadBrand::NintendoSwitch2 | GamepadBrand::NintendoGamecube | GamepadBrand::Playdate | GamepadBrand::SteamDeck | GamepadBrand::PlayStationSeries, GamepadButton::DPadRight) => Some(&[k::stem_words::_dpad, k::stem_words::_right]),
            (GamepadBrand::XboxSeries, GamepadButton::Other(_)) => None,
        }
    }
}