use bevy_input::keyboard::KeyCode;
#[cfg(feature = "use_kenney_input_prompts")]
use kenney_input_prompts::tokenize_dir::keyboard_and_mouse as ktd;

use crate::Pack;

pub fn from_key_code<'a, 'b>(version: Pack, key_code: KeyCode) -> Option<&'a [&'b [usize]]> {
    match version {
        #[cfg(feature = "use_kenney_input_prompts")]
        Pack::Kenney => match key_code {
            KeyCode::Backquote => Some(&[ktd::stem_word::_tilde, ktd::dir::_Keyboard___Mouse]),
            KeyCode::Backslash => Some(&[ktd::stem_word::_slash, ktd::dir::_Keyboard___Mouse]),
            KeyCode::BracketLeft => Some(&[
                ktd::stem_word::_bracket,
                ktd::stem_word::_open,
                ktd::dir::_Keyboard___Mouse,
            ]),
            KeyCode::BracketRight => Some(&[
                ktd::stem_word::_bracket,
                ktd::stem_word::_close,
                ktd::dir::_Keyboard___Mouse,
            ]),
            KeyCode::Comma => Some(&[ktd::stem_word::_comma, ktd::dir::_Keyboard___Mouse]),
            KeyCode::Digit0 => Some(&[ktd::stem_word::_0, ktd::dir::_Keyboard___Mouse]),
            KeyCode::Digit1 => Some(&[ktd::stem_word::_1, ktd::dir::_Keyboard___Mouse]),
            KeyCode::Digit2 => Some(&[ktd::stem_word::_2, ktd::dir::_Keyboard___Mouse]),
            KeyCode::Digit3 => Some(&[ktd::stem_word::_3, ktd::dir::_Keyboard___Mouse]),
            KeyCode::Digit4 => Some(&[ktd::stem_word::_4, ktd::dir::_Keyboard___Mouse]),
            KeyCode::Digit5 => Some(&[ktd::stem_word::_5, ktd::dir::_Keyboard___Mouse]),
            KeyCode::Digit6 => Some(&[ktd::stem_word::_6, ktd::dir::_Keyboard___Mouse]),
            KeyCode::Digit7 => Some(&[ktd::stem_word::_7, ktd::dir::_Keyboard___Mouse]),
            KeyCode::Digit8 => Some(&[ktd::stem_word::_8, ktd::dir::_Keyboard___Mouse]),
            KeyCode::Digit9 => Some(&[ktd::stem_word::_9, ktd::dir::_Keyboard___Mouse]),
            KeyCode::Equal => Some(&[ktd::stem_word::_equals, ktd::dir::_Keyboard___Mouse]),
            KeyCode::IntlBackslash => Some(&[ktd::stem_word::_slash, ktd::dir::_Keyboard___Mouse]),
            KeyCode::IntlRo => Some(&[ktd::stem_word::_slash, ktd::dir::_Keyboard___Mouse]),
            KeyCode::IntlYen => Some(&[ktd::stem_word::_slash, ktd::dir::_Keyboard___Mouse]),
            KeyCode::KeyA => Some(&[ktd::stem_word::_a, ktd::dir::_Keyboard___Mouse]),
            KeyCode::KeyB => Some(&[ktd::stem_word::_b, ktd::dir::_Keyboard___Mouse]),
            KeyCode::KeyC => Some(&[ktd::stem_word::_c, ktd::dir::_Keyboard___Mouse]),
            KeyCode::KeyD => Some(&[ktd::stem_word::_d, ktd::dir::_Keyboard___Mouse]),
            KeyCode::KeyE => Some(&[ktd::stem_word::_e, ktd::dir::_Keyboard___Mouse]),
            KeyCode::KeyF => Some(&[ktd::stem_word::_f, ktd::dir::_Keyboard___Mouse]),
            KeyCode::KeyG => Some(&[ktd::stem_word::_g, ktd::dir::_Keyboard___Mouse]),
            KeyCode::KeyH => Some(&[ktd::stem_word::_h, ktd::dir::_Keyboard___Mouse]),
            KeyCode::KeyI => Some(&[ktd::stem_word::_i, ktd::dir::_Keyboard___Mouse]),
            KeyCode::KeyJ => Some(&[ktd::stem_word::_j, ktd::dir::_Keyboard___Mouse]),
            KeyCode::KeyK => Some(&[ktd::stem_word::_k, ktd::dir::_Keyboard___Mouse]),
            KeyCode::KeyL => Some(&[ktd::stem_word::_l, ktd::dir::_Keyboard___Mouse]),
            KeyCode::KeyM => Some(&[ktd::stem_word::_m, ktd::dir::_Keyboard___Mouse]),
            KeyCode::KeyN => Some(&[ktd::stem_word::_n, ktd::dir::_Keyboard___Mouse]),
            KeyCode::KeyO => Some(&[ktd::stem_word::_o, ktd::dir::_Keyboard___Mouse]),
            KeyCode::KeyP => Some(&[ktd::stem_word::_p, ktd::dir::_Keyboard___Mouse]),
            KeyCode::KeyQ => Some(&[ktd::stem_word::_q, ktd::dir::_Keyboard___Mouse]),
            KeyCode::KeyR => Some(&[ktd::stem_word::_r, ktd::dir::_Keyboard___Mouse]),
            KeyCode::KeyS => Some(&[ktd::stem_word::_s, ktd::dir::_Keyboard___Mouse]),
            KeyCode::KeyT => Some(&[ktd::stem_word::_t, ktd::dir::_Keyboard___Mouse]),
            KeyCode::KeyU => Some(&[ktd::stem_word::_u, ktd::dir::_Keyboard___Mouse]),
            KeyCode::KeyV => Some(&[ktd::stem_word::_v, ktd::dir::_Keyboard___Mouse]),
            KeyCode::KeyW => Some(&[ktd::stem_word::_w, ktd::dir::_Keyboard___Mouse]),
            KeyCode::KeyX => Some(&[ktd::stem_word::_x, ktd::dir::_Keyboard___Mouse]),
            KeyCode::KeyY => Some(&[ktd::stem_word::_y, ktd::dir::_Keyboard___Mouse]),
            KeyCode::KeyZ => Some(&[ktd::stem_word::_z, ktd::dir::_Keyboard___Mouse]),
            KeyCode::Minus => Some(&[ktd::stem_word::_minus, ktd::dir::_Keyboard___Mouse]),
            KeyCode::Period => Some(&[ktd::stem_word::_period, ktd::dir::_Keyboard___Mouse]),
            KeyCode::Quote => Some(&[ktd::stem_word::_quote, ktd::dir::_Keyboard___Mouse]),
            KeyCode::Semicolon => Some(&[ktd::stem_word::_semicolon, ktd::dir::_Keyboard___Mouse]),
            KeyCode::Slash => Some(&[ktd::stem_word::_slash, ktd::dir::_Keyboard___Mouse]),
            KeyCode::AltLeft => Some(&[ktd::stem_word::_alt, ktd::dir::_Keyboard___Mouse]),
            KeyCode::AltRight => Some(&[ktd::stem_word::_alt, ktd::dir::_Keyboard___Mouse]),
            KeyCode::Backspace => Some(&[ktd::stem_word::_backspace, ktd::dir::_Keyboard___Mouse]),
            KeyCode::CapsLock => Some(&[ktd::stem_word::_capslock, ktd::dir::_Keyboard___Mouse]),
            KeyCode::ControlLeft => Some(&[ktd::stem_word::_ctrl, ktd::dir::_Keyboard___Mouse]),
            KeyCode::ControlRight => Some(&[ktd::stem_word::_ctrl, ktd::dir::_Keyboard___Mouse]),
            KeyCode::Enter => Some(&[ktd::stem_word::_enter, ktd::dir::_Keyboard___Mouse]),
            KeyCode::SuperLeft => Some(&[ktd::stem_word::_win, ktd::dir::_Keyboard___Mouse]),
            KeyCode::SuperRight => Some(&[ktd::stem_word::_win, ktd::dir::_Keyboard___Mouse]),
            KeyCode::ShiftLeft => Some(&[ktd::stem_word::_shift, ktd::dir::_Keyboard___Mouse]),
            KeyCode::ShiftRight => Some(&[ktd::stem_word::_shift, ktd::dir::_Keyboard___Mouse]),
            KeyCode::Space => Some(&[ktd::stem_word::_space, ktd::dir::_Keyboard___Mouse]),
            KeyCode::Tab => Some(&[ktd::stem_word::_tab, ktd::dir::_Keyboard___Mouse]),
            KeyCode::Delete => Some(&[ktd::stem_word::_delete, ktd::dir::_Keyboard___Mouse]),
            KeyCode::End => Some(&[ktd::stem_word::_end, ktd::dir::_Keyboard___Mouse]),
            KeyCode::Home => Some(&[ktd::stem_word::_home, ktd::dir::_Keyboard___Mouse]),
            KeyCode::Insert => Some(&[ktd::stem_word::_insert, ktd::dir::_Keyboard___Mouse]),
            KeyCode::PageDown => Some(&[
                ktd::stem_word::_page,
                ktd::stem_word::_down,
                ktd::dir::_Keyboard___Mouse,
            ]),
            KeyCode::PageUp => Some(&[
                ktd::stem_word::_page,
                ktd::stem_word::_up,
                ktd::dir::_Keyboard___Mouse,
            ]),
            KeyCode::ArrowDown => Some(&[
                ktd::stem_word::_arrow,
                ktd::stem_word::_down,
                ktd::dir::_Keyboard___Mouse,
            ]),
            KeyCode::ArrowLeft => Some(&[
                ktd::stem_word::_arrow,
                ktd::stem_word::_left,
                ktd::dir::_Keyboard___Mouse,
            ]),
            KeyCode::ArrowRight => Some(&[
                ktd::stem_word::_arrow,
                ktd::stem_word::_left,
                ktd::dir::_Keyboard___Mouse,
            ]),
            KeyCode::ArrowUp => Some(&[
                ktd::stem_word::_arrow,
                ktd::stem_word::_up,
                ktd::dir::_Keyboard___Mouse,
            ]),
            KeyCode::NumLock => Some(&[ktd::stem_word::_numlock, ktd::dir::_Keyboard___Mouse]),
            KeyCode::Numpad0 => Some(&[ktd::stem_word::_0, ktd::dir::_Keyboard___Mouse]),
            KeyCode::Numpad1 => Some(&[ktd::stem_word::_1, ktd::dir::_Keyboard___Mouse]),
            KeyCode::Numpad2 => Some(&[ktd::stem_word::_2, ktd::dir::_Keyboard___Mouse]),
            KeyCode::Numpad3 => Some(&[ktd::stem_word::_3, ktd::dir::_Keyboard___Mouse]),
            KeyCode::Numpad4 => Some(&[ktd::stem_word::_4, ktd::dir::_Keyboard___Mouse]),
            KeyCode::Numpad5 => Some(&[ktd::stem_word::_5, ktd::dir::_Keyboard___Mouse]),
            KeyCode::Numpad6 => Some(&[ktd::stem_word::_6, ktd::dir::_Keyboard___Mouse]),
            KeyCode::Numpad7 => Some(&[ktd::stem_word::_7, ktd::dir::_Keyboard___Mouse]),
            KeyCode::Numpad8 => Some(&[ktd::stem_word::_8, ktd::dir::_Keyboard___Mouse]),
            KeyCode::Numpad9 => Some(&[ktd::stem_word::_9, ktd::dir::_Keyboard___Mouse]),
            KeyCode::NumpadAdd => Some(&[
                ktd::stem_word::_numpad,
                ktd::stem_word::_plus,
                ktd::dir::_Keyboard___Mouse,
            ]),
            KeyCode::NumpadBackspace => {
                Some(&[ktd::stem_word::_backspace, ktd::dir::_Keyboard___Mouse])
            }
            KeyCode::NumpadComma => Some(&[ktd::stem_word::_comma, ktd::dir::_Keyboard___Mouse]),
            KeyCode::NumpadDecimal => Some(&[ktd::stem_word::_period, ktd::dir::_Keyboard___Mouse]),
            KeyCode::NumpadDivide => Some(&[ktd::stem_word::_slash, ktd::dir::_Keyboard___Mouse]),
            KeyCode::NumpadEnter => Some(&[
                ktd::stem_word::_numpad,
                ktd::stem_word::_enter,
                ktd::dir::_Keyboard___Mouse,
            ]),
            KeyCode::NumpadEqual => Some(&[ktd::stem_word::_equals, ktd::dir::_Keyboard___Mouse]),
            KeyCode::NumpadHash => Some(&[ktd::stem_word::_tilde, ktd::dir::_Keyboard___Mouse]),
            KeyCode::NumpadStar => Some(&[ktd::stem_word::_asterisk, ktd::dir::_Keyboard___Mouse]),
            KeyCode::NumpadSubtract => Some(&[ktd::stem_word::_minus, ktd::dir::_Keyboard___Mouse]),
            KeyCode::Escape => Some(&[ktd::stem_word::_escape, ktd::dir::_Keyboard___Mouse]),
            KeyCode::Fn => Some(&[ktd::stem_word::_function, ktd::dir::_Keyboard___Mouse]),
            KeyCode::PrintScreen => {
                Some(&[ktd::stem_word::_printscreen, ktd::dir::_Keyboard___Mouse])
            }
            KeyCode::Meta => Some(&[ktd::stem_word::_win, ktd::dir::_Keyboard___Mouse]),
            KeyCode::F1 => Some(&[ktd::stem_word::_f1, ktd::dir::_Keyboard___Mouse]),
            KeyCode::F2 => Some(&[ktd::stem_word::_f2, ktd::dir::_Keyboard___Mouse]),
            KeyCode::F3 => Some(&[ktd::stem_word::_f3, ktd::dir::_Keyboard___Mouse]),
            KeyCode::F4 => Some(&[ktd::stem_word::_f4, ktd::dir::_Keyboard___Mouse]),
            KeyCode::F5 => Some(&[ktd::stem_word::_f5, ktd::dir::_Keyboard___Mouse]),
            KeyCode::F6 => Some(&[ktd::stem_word::_f6, ktd::dir::_Keyboard___Mouse]),
            KeyCode::F7 => Some(&[ktd::stem_word::_f7, ktd::dir::_Keyboard___Mouse]),
            KeyCode::F8 => Some(&[ktd::stem_word::_f8, ktd::dir::_Keyboard___Mouse]),
            KeyCode::F9 => Some(&[ktd::stem_word::_f9, ktd::dir::_Keyboard___Mouse]),
            KeyCode::F10 => Some(&[ktd::stem_word::_f10, ktd::dir::_Keyboard___Mouse]),
            KeyCode::F11 => Some(&[ktd::stem_word::_f11, ktd::dir::_Keyboard___Mouse]),
            KeyCode::F12 => Some(&[ktd::stem_word::_f12, ktd::dir::_Keyboard___Mouse]),
            KeyCode::ContextMenu => None,
            KeyCode::Convert => None,
            KeyCode::KanaMode => None,
            KeyCode::Lang1 => None,
            KeyCode::Lang2 => None,
            KeyCode::Lang3 => None,
            KeyCode::Lang4 => None,
            KeyCode::Lang5 => None,
            KeyCode::NonConvert => None,
            KeyCode::Help => None,
            KeyCode::NumpadClear => None,
            KeyCode::NumpadClearEntry => None,
            KeyCode::NumpadMemoryAdd => None,
            KeyCode::NumpadMemoryClear => None,
            KeyCode::NumpadMemoryRecall => None,
            KeyCode::NumpadMemoryStore => None,
            KeyCode::NumpadMemorySubtract => None,
            KeyCode::NumpadMultiply => None,
            KeyCode::NumpadParenLeft => None,
            KeyCode::NumpadParenRight => None,
            KeyCode::FnLock => None,
            KeyCode::ScrollLock => None,
            KeyCode::Pause => None,
            KeyCode::BrowserBack => None,
            KeyCode::BrowserFavorites => None,
            KeyCode::BrowserForward => None,
            KeyCode::BrowserHome => None,
            KeyCode::BrowserRefresh => None,
            KeyCode::BrowserSearch => None,
            KeyCode::BrowserStop => None,
            KeyCode::Eject => None,
            KeyCode::LaunchApp1 => None,
            KeyCode::LaunchApp2 => None,
            KeyCode::LaunchMail => None,
            KeyCode::MediaPlayPause => None,
            KeyCode::MediaSelect => None,
            KeyCode::MediaStop => None,
            KeyCode::MediaTrackNext => None,
            KeyCode::MediaTrackPrevious => None,
            KeyCode::Power => None,
            KeyCode::Sleep => None,
            KeyCode::AudioVolumeDown => None,
            KeyCode::AudioVolumeMute => None,
            KeyCode::AudioVolumeUp => None,
            KeyCode::WakeUp => None,
            KeyCode::Hyper => None,
            KeyCode::Turbo => None,
            KeyCode::Abort => None,
            KeyCode::Resume => None,
            KeyCode::Suspend => None,
            KeyCode::Again => None,
            KeyCode::Copy => None,
            KeyCode::Cut => None,
            KeyCode::Find => None,
            KeyCode::Open => None,
            KeyCode::Paste => None,
            KeyCode::Props => None,
            KeyCode::Select => None,
            KeyCode::Undo => None,
            KeyCode::Hiragana => None,
            KeyCode::Katakana => None,
            KeyCode::F13 => None,
            KeyCode::F14 => None,
            KeyCode::F15 => None,
            KeyCode::F16 => None,
            KeyCode::F17 => None,
            KeyCode::F18 => None,
            KeyCode::F19 => None,
            KeyCode::F20 => None,
            KeyCode::F21 => None,
            KeyCode::F22 => None,
            KeyCode::F23 => None,
            KeyCode::F24 => None,
            KeyCode::F25 => None,
            KeyCode::F26 => None,
            KeyCode::F27 => None,
            KeyCode::F28 => None,
            KeyCode::F29 => None,
            KeyCode::F30 => None,
            KeyCode::F31 => None,
            KeyCode::F32 => None,
            KeyCode::F33 => None,
            KeyCode::F34 => None,
            KeyCode::F35 => None,
            KeyCode::Unidentified(_native_key_code) => None,
        },
    }
}
// match (version, key_code) {

// (Version::Xelu, KeyCode::Backquote) => Some(&[ktd::stem_word::_Tilda, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::Backslash) => Some(&[ktd::stem_word::_Slash, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::BracketLeft) => Some(&[ktd::stem_word::_Bracket, ktd::stem_word::_Left_0, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::BracketRight) => Some(&[ktd::stem_word::_Bracket, ktd::stem_word::_Right_0, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::Comma) => Some(&[ktd::stem_word::_Mark, ktd::stem_word::_Left_0, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::Digit0) => Some(&[ktd::stem_word::_0, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::Digit1) => Some(&[ktd::stem_word::_1, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::Digit2) => Some(&[ktd::stem_word::_2, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::Digit3) => Some(&[ktd::stem_word::_3, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::Digit4) => Some(&[ktd::stem_word::_4, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::Digit5) => Some(&[ktd::stem_word::_5, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::Digit6) => Some(&[ktd::stem_word::_6, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::Digit7) => Some(&[ktd::stem_word::_7, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::Digit8) => Some(&[ktd::stem_word::_8, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::Digit9) => Some(&[ktd::stem_word::_9, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::Equal) => Some(&[ktd::stem_word::_Plus, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::IntlBackslash) => Some(&[ktd::stem_word::_Slash, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::IntlRo) => Some(&[ktd::stem_word::_Slash, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::IntlYen) => Some(&[ktd::stem_word::_Slash, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::KeyA) => Some(&[ktd::stem_word::_A, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::KeyB) => Some(&[ktd::stem_word::_B, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::KeyC) => Some(&[ktd::stem_word::_C, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::KeyD) => Some(&[ktd::stem_word::_D, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::KeyE) => Some(&[ktd::stem_word::_E, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::KeyF) => Some(&[ktd::stem_word::_F, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::KeyG) => Some(&[ktd::stem_word::_G, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::KeyH) => Some(&[ktd::stem_word::_H, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::KeyI) => Some(&[ktd::stem_word::_I, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::KeyJ) => Some(&[ktd::stem_word::_J, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::KeyK) => Some(&[ktd::stem_word::_K, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::KeyL) => Some(&[ktd::stem_word::_L, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::KeyM) => Some(&[ktd::stem_word::_M, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::KeyN) => Some(&[ktd::stem_word::_N, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::KeyO) => Some(&[ktd::stem_word::_O, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::KeyP) => Some(&[ktd::stem_word::_P, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::KeyQ) => Some(&[ktd::stem_word::_Q, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::KeyR) => Some(&[ktd::stem_word::_R, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::KeyS) => Some(&[ktd::stem_word::_S, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::KeyT) => Some(&[ktd::stem_word::_T, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::KeyU) => Some(&[ktd::stem_word::_U, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::KeyV) => Some(&[ktd::stem_word::_V, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::KeyW) => Some(&[ktd::stem_word::_W, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::KeyX) => Some(&[ktd::stem_word::_X, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::KeyY) => Some(&[ktd::stem_word::_Y, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::KeyZ) => Some(&[ktd::stem_word::_Z, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::Minus) => Some(&[ktd::stem_word::_Minus, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::Period) => Some(&[ktd::stem_word::_Mark, ktd::stem_word::_Right_0, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::Quote) => Some(&[ktd::stem_word::_Quote, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::Semicolon) => Some(&[ktd::stem_word::_Semicolon, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::Slash) => Some(&[ktd::stem_word::_Slash, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::AltLeft) => Some(&[ktd::stem_word::_Alt, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::AltRight) => Some(&[ktd::stem_word::_Alt, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::Backspace) => Some(&[ktd::stem_word::_Backspace, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::CapsLock) => Some(&[ktd::stem_word::_Caps, ktd::stem_word::_Lock, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::ControlLeft) => Some(&[ktd::stem_word::_Ctrl, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::ControlRight) => Some(&[ktd::stem_word::_Ctrl, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::Enter) => Some(&[ktd::stem_word::_Enter, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::SuperLeft) => Some(&[ktd::stem_word::_Win, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::SuperRight) => Some(&[ktd::stem_word::_Win, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::ShiftLeft) => Some(&[ktd::stem_word::_Shift, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::ShiftRight) => Some(&[ktd::stem_word::_Shift, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::Space) => Some(&[ktd::stem_word::_Space, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::Tab) => Some(&[ktd::stem_word::_Tab, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::Delete) => Some(&[ktd::stem_word::_Del, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::End) => Some(&[ktd::stem_word::_End, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::Home) => Some(&[ktd::stem_word::_Home, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::Insert) => Some(&[ktd::stem_word::_Insert, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::PageDown) => Some(&[ktd::stem_word::_Page, ktd::stem_word::_Down, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::PageUp) => Some(&[ktd::stem_word::_Page, ktd::stem_word::_Up, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::ArrowDown) => Some(&[ktd::stem_word::_Arrow, ktd::stem_word::_Down, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::ArrowLeft) => Some(&[ktd::stem_word::_Arrow, ktd::stem_word::_Left_0, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::ArrowRight) => Some(&[ktd::stem_word::_Arrow, ktd::stem_word::_Right_0, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::ArrowUp) => Some(&[ktd::stem_word::_Arrow, ktd::stem_word::_Up, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::NumLock) => Some(&[ktd::stem_word::_Num, ktd::stem_word::_Lock, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::Numpad0) => Some(&[ktd::stem_word::_0, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::Numpad1) => Some(&[ktd::stem_word::_1, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::Numpad2) => Some(&[ktd::stem_word::_2, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::Numpad3) => Some(&[ktd::stem_word::_3, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::Numpad4) => Some(&[ktd::stem_word::_4, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::Numpad5) => Some(&[ktd::stem_word::_5, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::Numpad6) => Some(&[ktd::stem_word::_6, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::Numpad7) => Some(&[ktd::stem_word::_7, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::Numpad8) => Some(&[ktd::stem_word::_8, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::Numpad9) => Some(&[ktd::stem_word::_9, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::NumpadAdd) => Some(&[ktd::stem_word::_Plus, ktd::stem_word::_Tall, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::NumpadBackspace) => Some(&[ktd::stem_word::_Backspace, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::NumpadComma) => Some(&[ktd::stem_word::_Comma, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::NumpadDivide) => Some(&[ktd::stem_word::_Slash, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::NumpadEnter) => Some(&[ktd::stem_word::_Enter, ktd::stem_word::_Tall, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::NumpadHash) => Some(&[ktd::stem_word::_Tilda, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::NumpadStar) => Some(&[ktd::stem_word::_Asterisk, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::NumpadSubtract) => Some(&[ktd::stem_word::_Minus, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::Escape) => Some(&[ktd::stem_word::_Esc, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::PrintScreen) => Some(&[ktd::stem_word::_Print, ktd::stem_word::_Screen, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::Meta) => Some(&[ktd::stem_word::_Win, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::F1) => Some(&[ktd::stem_word::_F1, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::F2) => Some(&[ktd::stem_word::_F2, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::F3) => Some(&[ktd::stem_word::_F3, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::F4) => Some(&[ktd::stem_word::_F4, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::F5) => Some(&[ktd::stem_word::_F5, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::F6) => Some(&[ktd::stem_word::_F6, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::F7) => Some(&[ktd::stem_word::_F7, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::F8) => Some(&[ktd::stem_word::_F8, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::F9) => Some(&[ktd::stem_word::_F9, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::F10) => Some(&[ktd::stem_word::_F10, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::F11) => Some(&[ktd::stem_word::_F11, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::F12) => Some(&[ktd::stem_word::_F12, ktd::dir::_Xelu_Free_Controller_Key_Prompts, ktd::dir::_Keyboard___Mouse]),
// (Version::Xelu, KeyCode::NumpadDecimal) => None,
// (Version::Xelu, KeyCode::NumpadEqual) => None,
// (Version::Xelu, KeyCode::Fn) => None,
// (Version::Xelu, KeyCode::ContextMenu) => None,
// (Version::Xelu, KeyCode::Convert) => None,
// (Version::Xelu, KeyCode::KanaMode) => None,
// (Version::Xelu, KeyCode::Lang1) => None,
// (Version::Xelu, KeyCode::Lang2) => None,
// (Version::Xelu, KeyCode::Lang3) => None,
// (Version::Xelu, KeyCode::Lang4) => None,
// (Version::Xelu, KeyCode::Lang5) => None,
// (Version::Xelu, KeyCode::NonConvert) => None,
// (Version::Xelu, KeyCode::Help) => None,
// (Version::Xelu, KeyCode::NumpadClear) => None,
// (Version::Xelu, KeyCode::NumpadClearEntry) => None,
// (Version::Xelu, KeyCode::NumpadMemoryAdd) => None,
// (Version::Xelu, KeyCode::NumpadMemoryClear) => None,
// (Version::Xelu, KeyCode::NumpadMemoryRecall) => None,
// (Version::Xelu, KeyCode::NumpadMemoryStore) => None,
// (Version::Xelu, KeyCode::NumpadMemorySubtract) => None,
// (Version::Xelu, KeyCode::NumpadMultiply) => None,
// (Version::Xelu, KeyCode::NumpadParenLeft) => None,
// (Version::Xelu, KeyCode::NumpadParenRight) => None,
// (Version::Xelu, KeyCode::FnLock) => None,
// (Version::Xelu, KeyCode::ScrollLock) => None,
// (Version::Xelu, KeyCode::Pause) => None,
// (Version::Xelu, KeyCode::BrowserBack) => None,
// (Version::Xelu, KeyCode::BrowserFavorites) => None,
// (Version::Xelu, KeyCode::BrowserForward) => None,
// (Version::Xelu, KeyCode::BrowserHome) => None,
// (Version::Xelu, KeyCode::BrowserRefresh) => None,
// (Version::Xelu, KeyCode::BrowserSearch) => None,
// (Version::Xelu, KeyCode::BrowserStop) => None,
// (Version::Xelu, KeyCode::Eject) => None,
// (Version::Xelu, KeyCode::LaunchApp1) => None,
// (Version::Xelu, KeyCode::LaunchApp2) => None,
// (Version::Xelu, KeyCode::LaunchMail) => None,
// (Version::Xelu, KeyCode::MediaPlayPause) => None,
// (Version::Xelu, KeyCode::MediaSelect) => None,
// (Version::Xelu, KeyCode::MediaStop) => None,
// (Version::Xelu, KeyCode::MediaTrackNext) => None,
// (Version::Xelu, KeyCode::MediaTrackPrevious) => None,
// (Version::Xelu, KeyCode::Power) => None,
// (Version::Xelu, KeyCode::Sleep) => None,
// (Version::Xelu, KeyCode::AudioVolumeDown) => None,
// (Version::Xelu, KeyCode::AudioVolumeMute) => None,
// (Version::Xelu, KeyCode::AudioVolumeUp) => None,
// (Version::Xelu, KeyCode::WakeUp) => None,
// (Version::Xelu, KeyCode::Hyper) => None,
// (Version::Xelu, KeyCode::Turbo) => None,
// (Version::Xelu, KeyCode::Abort) => None,
// (Version::Xelu, KeyCode::Resume) => None,
// (Version::Xelu, KeyCode::Suspend) => None,
// (Version::Xelu, KeyCode::Again) => None,
// (Version::Xelu, KeyCode::Copy) => None,
// (Version::Xelu, KeyCode::Cut) => None,
// (Version::Xelu, KeyCode::Find) => None,
// (Version::Xelu, KeyCode::Open) => None,
// (Version::Xelu, KeyCode::Paste) => None,
// (Version::Xelu, KeyCode::Props) => None,
// (Version::Xelu, KeyCode::Select) => None,
// (Version::Xelu, KeyCode::Undo) => None,
// (Version::Xelu, KeyCode::Hiragana) => None,
// (Version::Xelu, KeyCode::Katakana) => None,
// (Version::Xelu, KeyCode::F13) => None,
// (Version::Xelu, KeyCode::F14) => None,
// (Version::Xelu, KeyCode::F15) => None,
// (Version::Xelu, KeyCode::F16) => None,
// (Version::Xelu, KeyCode::F17) => None,
// (Version::Xelu, KeyCode::F18) => None,
// (Version::Xelu, KeyCode::F19) => None,
// (Version::Xelu, KeyCode::F20) => None,
// (Version::Xelu, KeyCode::F21) => None,
// (Version::Xelu, KeyCode::F22) => None,
// (Version::Xelu, KeyCode::F23) => None,
// (Version::Xelu, KeyCode::F24) => None,
// (Version::Xelu, KeyCode::F25) => None,
// (Version::Xelu, KeyCode::F26) => None,
// (Version::Xelu, KeyCode::F27) => None,
// (Version::Xelu, KeyCode::F28) => None,
// (Version::Xelu, KeyCode::F29) => None,
// (Version::Xelu, KeyCode::F30) => None,
// (Version::Xelu, KeyCode::F31) => None,
// (Version::Xelu, KeyCode::F32) => None,
// (Version::Xelu, KeyCode::F33) => None,
// (Version::Xelu, KeyCode::F34) => None,
// (Version::Xelu, KeyCode::F35) => None,
// (Version::Xelu, KeyCode::Unidentified(_native_key_code)) => None,
// }
